version: "3.2"
services:
 #........................ rabbit .....................
  broker:
    container_name: 'rabbit'
    image: rabbit_image
    restart: always 
    ports:
        - 1883:1883
        - 5672:5672
        - 15672:15672
    build: 
      context: .
      dockerfile: rabbit/Dockerfile
    networks:
      default:
        aliases:
          - rabbit
 #........................ influx .....................
  database:
    container_name: influx
    image: influx_image
    restart: always 
    ports:
        - 8086:8086
    build: 
      context: .
      dockerfile: influx/Dockerfile
    env_file:
      - influx/setup.env
    networks:
      default:
        aliases:
          - influx
  #........................ telegraf .....................
  telegraf:
      container_name: telegraf
      image: telegraf-image
      restart: always
      build:
        context: .
        dockerfile: telegraf/Dockerfile
      volumes:
        - ./telegraf/telegra.conf:/etc/telegraf/telegraf.conf
      depends_on:
        - database
  #........................ grafana .....................  
  
  visualizador:
    container_name: grafana
    image: grafana-image
    restart: always
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: grafana/Dockerfile
    depends_on:
      - database
  
 #........................ analitica .....................  

  analitica:
    container_name: analitica
    image: analitica-image
    restart: always
    build:
      context: .
      dockerfile: analitica/Dockerfile
    depends_on:
      - database



 


 